title: "MATG1058 - Optimización Numérica"
logo: images/logo.png
execute:
  execute_notebooks: "off"
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - dollarmath
    - amsmath
    - deflist